from collections import Counter

import sys
import numpy as np
import librosa

class NoteDetector:
    """
    Class to detect musical notes and estimate key from an audio file. Generated by Copilot mostly :)
    """
    NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    MAJOR_PROFILE = np.array([6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88])
    MINOR_PROFILE = np.array([6.33,2.68,3.52,5.38,2.60,3.53,2.54,4.75,3.98,2.69,3.34,3.17])

    def __init__(self, hop_length=512, sample_rate=44100):
        self.hop_length = hop_length
        self.sample_rate = sample_rate

    def hz_to_note_name(self, hz):
        """
        Convert frequency in Hz to note name (e.g. A4, C#3). Returns None if out of MIDI range.
        """
        if hz <= 0: return None
        midi = int(round(69 + 12*np.log2(hz/440.0)))
        if midi < 0 or midi > 127: 
            return None
        name = NoteDetector.NOTE_NAMES[midi % 12]
        octave = midi//12 - 1
        return f"{name}{octave}"
    
    def estimate_key(self, pitches):
        """pitches: list of MIDI pitch classes (0-11) counts"""
        profile = np.array([pitches.get(i,0) for i in range(12)], dtype=float)
        if profile.sum() == 0:
            return None
        profile = (profile / profile.sum())*100
        best_score = -1e9
        for root in range(12):
            major = np.roll(NoteDetector.MAJOR_PROFILE, root)
            minor = np.roll(NoteDetector.MINOR_PROFILE, root)
            s_maj = np.corrcoef(profile, major)[0,1]
            s_min = np.corrcoef(profile, minor)[0,1]
            if s_maj > best_score:
                best_score = s_maj
                best = (root, 'major', s_maj)
            if s_min > best_score:
                best_score = s_min
                best = (root, 'minor', s_min)
        root, mode, score = best
        return f"{NoteDetector.NOTE_NAMES[root]} {mode}", score

    def detect_notes(self, audio_path):
        """
        Analyze the audio file to detect notes and estimate key.
        Returns a dict with file info, estimated key, and note timeline.
        """
        y, sr = librosa.load(audio_path, sr=self.sample_rate, mono=True)
        f0, voiced_flag, voiced_prob = librosa.pyin(y, fmin=librosa.note_to_hz('C2'),
                                                fmax=librosa.note_to_hz('C7'),
                                                sr=sr, hop_length=self.hop_length)
        times = librosa.frames_to_time(np.arange(len(f0)), sr=sr, hop_length=self.hop_length)
        # Build note timeline and pitch-class histogram
        note_timeline = []
        pc_counts = Counter()
        for t, f in zip(times, f0):
            if np.isnan(f):
                note_timeline.append((t, None))
            else:
                name = self.hz_to_note_name(f)
                note_timeline.append((t, name))
                # update pitch class
                midi = int(round(69 + 12*np.log2(f/440.0)))
                pc = midi % 12
                pc_counts[pc] += 1
        key_est, score = self.estimate_key(pc_counts) or ("Unknown", 0)
        print(f"Estimated key: {key_est} (score {score:.3f})")
        return {
            'file': audio_path,
            'sr': sr,
            'hop_length': self.hop_length,
            'key': key_est,
            'key_score': float(score),
            'note_timeline': note_timeline
        }
    
    def pretty_print(self, result, max_rows=200):
        """
        Nicely print the detection results.
        """
        print(f"File: {result['file']}")
        print(f"Estimated key: {result['key']} (score {result['key_score']:.3f})")
        print("\nTime (s)    Note")
        for t, n in result['note_timeline'][:max_rows]:
            note = n if n is not None else '-'
            print(f"{t:7.3f}    {note}")
        if len(result['note_timeline']) > max_rows:
            print(f"... ({len(result['note_timeline'])} total frames)")

if __name__ == "__main__":
    detector = NoteDetector()
    if len(sys.argv) < 2:
        print("Usage: python pitchplay.py path/to/audiofile")
        sys.exit(1)
    path = sys.argv[1]
    res = detector.detect_notes(path)
    detector.pretty_print(res)